USE shopping_cart;

INSERT INTO shopping_cart
(id, name, price, import_type, category, image_url, quantity)
Values
(1, "Salmon",  15.99, "domestic", "food" , "../../assets/images/salmon.jpg", 50),
(2, "Avocado",  0.99, "domestic", "food" , "../../assets/images/avocado.jpg", 59),
(3, "Ancient Grains",  6.45, "domestic", "food" , "../../assets/images/grains.jpg", 100),
(4, "Blueberries",  2.99, "domestic", "food" , "../../assets/images/blueberries.jpg", 24),
(5, "Belgium Chocolate",  15.50, "imported", "food" , " ../../assets/images/chocolate.jpg ", 48),
(6, "Almonds",  4.99, "domestic", "food" , " ../../assets/images/almonds.jpg ", 75),
(7, "Coconut",  6.25, "domestic", "food" , "../../assets/images/coconut.jpg", 51),
(8, "Apple",  3.75, "domestic", "food", "../../assets/images/apples.png", 88),
(9, "Pomegranates",  1.99, "domestic", "food" , " ../../assets/images/pomegranate.jpg", 94),
(10, "Omelette",  4.25, "domestic", "food" , "  ../../assets/images/omelette.jpg", 100),
(11, "Super Green Detox Mix",  29.90, "domestic", "medical", " ../../assets/images/superGreen.jpg ", 24),
(12, "Biotin 2,500mg",  18.00, "domestic", "medical" , "../../assets/images/biotin.jpeg", 50),
(13, "Fish oil 2400mg", 21.49  , "domestic", "medical" , " ../../assets/images/fishOil.png", 61 ),
(14, "Neutrogena Sunscreen 70SPF",  8.97, "domestic", "medical" , "../../assets/images/sunscreen.jpeg", 34),
(15, "Dr Tobias Multivitamin",  23.97, "domestic", "medical" , "../../assets/images/multivitamin.jpg", 35),
(16, "Band-Aids",  14.24, "domestic", "medical" , "../../assets/images/bandaid.jpg", 50),
(17, "Aloe Vera Gel",  11.55, "domestic", "medical" , "../../assets/images/aloe.jpg", 21),
(18, "Hydrogen Peroxide",  6.48, "domestic", "medical" , "../../assets/images/hydrogen.jpg", 12),
(19, "BC Powder",  4.19, "domestic", "medical" , "../../assets/images/bcpowder.jpg", 112),
(20, "Alka-Seltzer Plus",  7.99, "domestic", "medical" , "../../assets/images/alkaseltzer.jpg", 55),
(21, "Luciano Pavarotti", 12.59, "domestic", "music" , "../../assets/images/luciano.jpg", 6),
(22, "Jill Scott", 13.41, "domestic", "music" , "../../assets/images/jill.jpg", 5),
(23, "Queen", 13.99, "domestic", "music" , "../../assets/images/queen.jpg", 15),
(24, "West Side Story", 9.96, "domestic", "music" , "../../assets/images/westside.jpg", 4),
(25, "Frank Sinatra", 10.17, "domestic", "music" , "../../assets/images/frank.jpg", 40),
(26, "A Tribe Called Quest", 13.99, "domestic", "music" , "../../assets/images/tribe.jpg", 11),
(27, "Bob Marley", 14.98, "domestic", "music" , "../../assets/images/bob.jpg", 10),
(28, "Michael Jackson", 15.14, "domestic", "music" , "../../assets/images/michael.jpg", 25),
(29, "Phantom Of The Opera", 12.59, "domestic", "music" , "../../assets/images/phantom.jpg", 4),
(30, "Musiq Soulchild", 13.59, "domestic", "music" , "../../assets/images/musiq.jpg", 14),
(31, "Manolo Hangisi", 995.00, "imported", "luxury" , "../../assets/images/yellowMano.jpg", 3),
(32, "Manolo Satin Nadira", 1030.00, "imported", "luxury" , "../../assets/images/blackMano.jpg", 10),
(33, "Tiffany  Atlas ", 5300.00, "domestic", "luxury" , "../../assets/images/tiffWatch.jpg", 22),
(34, "Tiffany Metro", 9450.00, "domestic", "luxury" , "../../assets/images/tiffWatch2.jpg", 11),
(35, "Balenciaga Hourglass", 1490.00, "imported", "luxury" , "../../assets/images/hourglass.jpg", 23),
(36, "Louis Vuitton Bumbag", 1820.00, "imported", "luxury" , "../../assets/images/louis.jpg", 18),
(37, "Cartier Panthere", 718.00, "imported", "luxury" , "../../assets/images/panther.jpg", 19),
(38, "Chanel Silver and Pink", 545.00, "imported", "luxury" , "../../assets/images/chanel.jpg", 22),
(39, "Gucci Running G", 1450.00, "imported", "luxury" , "../../assets/images/gucci.jpg", 13),
(40, "Suzanne Kalan 18K Rose Gold", 1800.00, "imported", "luxury" , "../../assets/images/necklace.jpg", 20),
(41, "XSCAPE X Gown", 139.99, "domestic", "clothing" , "../../assets/images/dress.jpg", 23),
(42, "SL Fashions Floral Dress", 88.99, "domestic", "clothing" , "../../assets/images/dress2.jpg", 31),
(43, "JM Collection Top", 49.50, "domestic", "clothing" , "../../assets/images/blouse.jpg", 17), 
(44, "INC International Top", 69.50, "domestic", "clothing" , "../../assets/images/blouse2.jpg", 24), 
(45, "Style Co Jeans", 49.00, "domestic", "clothing" , "../../assets/images/jeans.jpg", 21), 
(46, "Levi’s Jeans", 59.50, "domestic", "clothing" , "../../assets/images/pants.jpg", 29), 
(47, "Nike Vintage Pants", 55.50, "domestic", "clothing" , "../../assets/images/nike2.jpg", 42), 
(48, "Nike Essential Cotton Tank", 55.50, "domestic", "clothing" , "../../assets/images/nike.jpg", 22), 
(49, "Eagles Women’s Long Sleeve Top", 55.50, "domestic", "clothing", "../../assets/images/eagles.jpg", 31), 
(50, "Nike Wentz Eagles Jersey", 100.00, "domestic", "clothing" , "../../assets/images/wentz.jpg", 11),
(51, "The Power of Habits",  8.99,  "domestic", "books","../../assets/images/habits.jpg", 14),
(52, "Daring Greatly",  21.82, "domestic", "books", "../../assets/images/daring.jpg", 20),
(53, "The Power Of TED",  14.44, "domestic", "books", "../../assets/images/ted.jpg",25),
(54, "What Self-Made Millionaires..",  15.26, "domestic", "books", " ../../assets/images/millionaire.jpg", 25),
(55, "Motivating Millennials",  14.24, "domestic", "books", " ../../assets/images/motivating.jpg", 22),
(56, "Examinations in Cyber Security",  225.00, "domestic", "books", " ../../assets/images/cyber.jpg", 25),
(57, "Cyber War",  15.29, "domestic", "books", " ../../assets/images/war.jpg", 25),
(58, "Complete Poetry of..", 14.95, "domestic", "books", " ../../assets/images/edgar.jpg", 25),
(59, "Aesop's Fables",  14.99, "domestic", "books", " ../../assets/images/aesop.jpg", 25),
(60, "A Tale of Two Cities",  21.94, "domestic", "books", " ../../assets/images/tale.jpg", 25)